### ISSUE TITLE
Test is not really testing 

### ISSUE THREAD

**Issue by twittidai** [envelope-project/laik#10]
Success even with:

mpirun -np 4 ../../examples/vsum | sort > test-vsum.out
== LAIK-003.00 T 0/4 0001.01 task-wise  ERROR  : laik_map called for data 'data-0' defined on task group 1.
== LAIK-003.00 T 0/4 0001.02 task-wise         : This task is NOT part of the group. Fix your application!
== LAIK-003.00 T 0/4 0001.03 task-wise         : (may crash now if returned address is dereferenced)
cmp test-vsum.out test-vsum.expected

**Comment by weidendo** [comment]
This is a wrong use of the LAIK API by the application: a collective operation (that is, to be called by
all members of a group) was issued by a task which is not part of the group.
It is not clear to me whether this always should be fatal (and resulting in a test failure),
as LAIK can just ignore this, and the application/test still works.

Being fatal may be the sensible thing to do, so keep this issue open as reminder to fix the vsum example....

**Comment by twittidai** [comment]
fixed

**Comment by weidendo** [comment]
Now fixed.
