### ISSUE TITLE
make -j does not work

### ISSUE THREAD

**Issue by twittidai** [envelope-project/laik#112]
With LAIK makefile, this does not work. 
You need to link first...

mpicc -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c -o src/backend-mpi.o src/backend-mpi.c
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/backend.c -o src/backend.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/core.c -o src/core.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/data.c -o src/data.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/debug.c -o src/debug.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/external.c -o src/external.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/partitioner.c -o src/partitioner.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/partitioning.c -o src/partitioning.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/profiling.c -o src/profiling.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/program.c -o src/program.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/space.c -o src/space.o
cc -c -O0 -g -Wall -Wextra -DUSE_MPI -std=gnu99 -Iinclude -Isrc -fPIC -MMD -MP -c src/type.c -o src/type.o
cd examples/c++ && /Library/Developer/CommandLineTools/usr/bin/make
make[1]: *** No rule to make target `/Users/yang/play/laik/liblaik.so', needed by `raytracer'.  Stop.
make: *** [examples/c++] Error 2
make: *** Waiting for unfinished jobs....

**Comment by weidendo** [comment]
Fixed in 0b8fabdcb
