### ISSUE TITLE
TCP backend: fails to compile with ICC

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#128]
See https://github.com/envelope-project/laik/pull/58#issuecomment-375386563

**Comment by weidendo** [comment]
Do you have access to icc? I do not think we can integrate icc in Travis?

**Comment by AlexanderKurtz** [comment]
I currently trying to debug this and I think I have an idea: Did you do your ICC test on the SuperMUC?

**Comment by AlexanderKurtz** [comment]
From what I can tell now, there was never any problem with ICC and the TCP backend. It just so happened that the ICC builds were always done on machines with a very old GLib, and this of course didn't work. Since the GLib version is now checked (2bfd2b684c7a48b13db0cb179c01566f056d2d77), I'm closing this bug now, please feel free to reopen if necessary!
