### ISSUE TITLE
TCP backend: fails to compile on MacOS

### ISSUE THREAD

**Issue by weidendo** [envelope-project/laik#131]
src/backends/tcp/minimpi.c:2:10: fatal error: 'endian.h' file not
      found
#include <endian.h>     // for htole64, htobe64
         ^~~~~~~~~~
1 error generated.

There is a /usr/include/machine/endian.h on macOS, but this does not define htole64/htobe64.
Can you implement these yourself?

**Comment by weidendo** [comment]
The endian stuff is solved, but the issue not yet.
No it errors on macOS with the following. Is this Linux-specific?

src/backends/tcp/socket.c:45:44: error: use of undeclared identifier
      'MSG_NOSIGNAL'
        return send (this->fd, data, size, MSG_NOSIGNAL) == (ssize_t) size;
                                           ^
src/backends/tcp/socket.c:201:42: error: use of undeclared identifier
      'TCP_KEEPIDLE'
        if (setsockopt (fd, IPPROTO_TCP, TCP_KEEPIDLE, & (int) { config-...

**Comment by weidendo** [comment]
Sorry, need to reopen again. It compiles, but already the first test fails now:

tcp/./jac1d_1000_50_10.sh
[LAIK TCP Backend] Aborting, the contents of the error stack follow:
 => Domain laik_init_tcp encountered error #1: Failed to initialize the MPI subsystem
 => Domain laik_tcp_backend_push_code encountered error #0: An MPI operation failed, details below
 => Domain laik_tcp_minimpi_init encountered error #1: Could not bind any task address
 => Domain laik_tcp_socket_new encountered error #11: Failed to bind socket to 'laik-tcp-auto-openmpi-68896-3': No such file or directory

**Comment by weidendo** [comment]
Here is the output of dtruss (the equivalent of strace):

socket(0x1, 0x1, 0x0)		 = 3 0
setsockopt(0x3, 0xFFFF, 0x1022)		 = 0 0
bind(0x3, 0x7F8FDAC12BF0, 0x1C)		 = -1 Err#2
close(0x3)		 = 0 0

Obviously bind() fails as the error above already tells.

**Comment by AlexanderKurtz** [comment]
I have an idea why this fails: The code uses abstract UNIX sockets (i.e. UNIX sockets which are bound to a name but not a file) and this is probably a Linux-only feature...

**Comment by weidendo** [comment]
Ah, ok.
How difficult is it to support regular UNIX domain sockets?
Or how can I force real TCP sockets to be used?

**Comment by AlexanderKurtz** [comment]
This bug was about compilation errors on OSX; these were [successfully fixed](https://github.com/envelope-project/laik/pull/136#issuecomment-376954474) by #134 and #136, so let's close this issue now! The UNIX socket issue is an entirely different problem and I have just opened #142 for it!

**Comment by weidendo** [comment]
Compiling without working is useless, but as you like.
