### ISSUE TITLE
TCP backend: does not work on MacOS

### ISSUE THREAD

**Issue by weidendo** [envelope-project/laik#144]
It is expected that the TCP backend does not work when using UNIX domain sockets, as it
uses linux-specific "abstract" UNIX domains sockets.

However, forcing TCP sockets via a config file with

    0 = localhost 4444
    1 = localhost 4445

does not work either. Both processes hang on each example.
Will provide details soon.

**Comment by AlexanderKurtz** [comment]
Could you try something like this with the latest master?

```
$ cat config.txt 
[general]
# nothing here

[addresses]
rank0 = localhost 2000
rank1 = localhost 2001
$ export LAIK_BACKEND=tcp LAIK_TCP_CONFIG=config.txt 
$ time ( examples/jac3d 300 & examples/jac3d 300; wait )
300 x 300 x 300 cells (mem 432.0 MB), running 50 iterations with 2 tasks
Residuum after  1 iters: 81833143.888938
Residuum after 11 iters: 145928.481950
Residuum after 21 iters: 34990.353157
Residuum after 31 iters: 19320.487049
Residuum after 41 iters: 12616.052283

real	0m9.135s
user	0m18.030s
sys	0m0.208s
$ 
```

**Comment by weidendo** [comment]
Works, nice!

Now I can try to couple my Dell and my Mac laptops.
Perhaps we need to get automatic load balancing working :-)
