### ISSUE TITLE
MPI tests fail with OpenMPI 3.0 because --oversubscribe is not specified

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#155]
Beginning with version 3.0, OpenMPI's mpirun refuses to start more processes than there are physical processor cores on the machine:

```
$ mpirun --version
mpirun (Open MPI) 3.0.1

Report bugs to http://www.open-mpi.org/community/help/
$ mpirun -np 1 true
$ mpirun -np 2 true
$ mpirun -np 3 true
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 3 slots
that were requested by the application:
  true

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
$ mpirun -np 3 --oversubscribe true
$ 
```

Since the MPI test do not specify the ```--oversubscribe``` option, this change breaks these tests on all 
machines with <4 processors cores, i.e. most laptops but also [Travis](https://docs.travis-ci.com/user/reference/overview/).

I have a PR ready which (among other things) fixes this, stay tuned!

**Comment by weidendo** [comment]
Travis does not seem to be broken?

**Comment by AlexanderKurtz** [comment]
Travis currently uses Debian Stretch and Ubuntu 16.04 which both don't contain OpenMPI 3.0, so Travis is fine for now. However, it will be affected when we upgrade the test distros in the Dockerfile. For now, this is mostly a potential problem for new contributors, so I thought I'd mention it here!

**Comment by weidendo** [comment]
I see.

As long as we can influence mpiexec arguments of the test runs via environment variables (and we
can, now) we are fine, which enables setting them via the Dockerfile or even travis.yaml.

**Comment by AlexanderKurtz** [comment]
Right, so I'm closing this now!
