### ISSUE TITLE
Tests for TCP backend do not work on Mac

### ISSUE THREAD

**Issue by weidendo** [envelope-project/laik#157]
The TCP backend obviously can work on Macs, but the tests are using the Linux-specific abstract unix sockets, resulting in the tests to fail:

    /Library/Developer/CommandLineTools/usr/bin/make -C tcp
    ./jac1d_1000_50_10.sh
    [LAIK TCP Backend] Aborting, the contents of the error stack follow:
     => Domain laik_init_tcp encountered error #1: Failed to initialize the MPI subsystem.
     => Domain laik_tcp_backend_push_code encountered error #0: An MPI operation failed, details below
     => Domain laik_tcp_minimpi_init encountered error #0: Could not bind any task address
     => Domain laik_tcp_socket_new encountered error #11: Failed to bind socket to 'laik-tcp-auto-openmpi-6773-3': No such file or directory
     => Domain laik_tcp_socket_new encountered error #11: Failed to bind socket to 'laik-tcp-auto-openmpi-6773-2': No such file or directory
     => Domain laik_tcp_socket_new encountered error #11: Failed to bind socket to 'laik-tcp-auto-openmpi-6773-1': No such file or directory
     => Domain laik_tcp_socket_new encountered error #11: Failed to bind socket to 'laik-tcp-auto-openmpi-6773-0': No such file or directory

Tests should use TCP.

**Comment by AlexanderKurtz** [comment]
> Tests should use TCP.

Yeah, I figure we should probably get rid of the Unix sockets completely. They were a nice help during development, but they cause problems like this and complicate the code quite a bit. And after all, it's called the *TCP* backend!

However, there is one problem: What ports should the tests use then? Because simply having a configuration file like this one

```
[addresses]
rank0 = localhost 2000
rank1 = localhost 2001
rank2 = localhost 2002
rank3 = localhost 2003
```

would mean that the tests break on system which use these ports for something else **and** that the tests could no longer be run in parallel. Any good ideas?

**Comment by twittidai** [comment]
> However, there is one problem: What ports should the tests use then? Because simply having a configuration file like this one

In general a higher port number decreases the change of port collision.
However, this is something that the magic ochestrator need to do, not the user. Unless we implement the ochestrator, I suggerst to leave it be.

**Comment by weidendo** [comment]
I think the range 2000+ is fine for the tests.
It is much better than the current situation, where tests do not run on macOS.

**Comment by weidendo** [comment]
If we want macOS to be supported, of course the test suite must run successfully.
So this must be flagged as bug.
