### ISSUE TITLE
src/external.c decides at runtime whether a pointer is a string or a function

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#38]
```src/external.c``` currently contains this code:

```
    if(!isDynamic){
        init = (laik_agent_init) name;
    }else{
        path = (char*) name;
        handle = dlopen(path, RTLD_LAZY);
        if(!handle){
            laik_log(LAIK_LL_Error, dlerror());
            exit(1);
        }
        init = (laik_agent_init) probfunc(handle, "agent_init");
        assert(init);
    }
```

This code essentially decides **at runtime** whether a pointer is a string or a function. I really don't think this is a good idea, and the compiler als trips over this¹. Can we find a better solution here?

[1] https://travis-ci.org/envelope-project/laik/jobs/308053895#L833

**Comment by AlexanderKurtz** [comment]
https://stackoverflow.com/questions/14134245/iso-c-void-and-function-pointers looks interesting...

**Comment by weidendo** [comment]
@twittidai I agree with Alex. For some architecture, code pointers may have different size/format than data pointers: think about x86-32 segmented addressing with a "small code/large data" addressing model, requiring far pointers (64 bit) for data, but 32bit pointers for code. At least that is my understanding why ISO C forbids such code...
