### ISSUE TITLE
Finalize MPI backend for 1. release

### ISSUE THREAD

**Issue by twittidai** [envelope-project/laik#4]
Must be done @1. priority!

**Comment by weidendo** [comment]
Strange.
For each new functionality in LAIK, we may require an extension of an interface. Thus, an implementation of an interface never is really finished. @twittidai Close?

**Comment by twittidai** [comment]
No, What I mean is to finalise the MPI Backend for the "first" release, which clearly can be done in the near future. 
I change the name. happy now?

**Comment by twittidai** [comment]
According to @weidendo, an backend cannot finish because it is required for each extension of an interface
