### ISSUE TITLE
CLOCK_MONOTONIC_COARSE does not work on SLES linux / macOS

### ISSUE THREAD

**Issue by twittidai** [envelope-project/laik#45]
src/profiling.c: In function 'laik_fast_realtime':
src/profiling.c:83:19: error: 'CLOCK_MONOTONIC_COARSE' undeclared (first use in this function); did you mean 'CLOCK_MONOTONIC'?
     clock_gettime(CLOCK_MONOTONIC_COARSE, &tv);
                   ^~~~~~~~~~~~~~~~~~~~~~
                   CLOCK_MONOTONIC
src/profiling.c:83:19: note: each undeclared identifier is reported only once for each function it appears in

**Comment by weidendo** [comment]
What was the point not to always use gettimeofday?

**Comment by twittidai** [comment]
The background was to provide different clocks with different speed (refer to discussion). 
I will fix this in the near future.

**Comment by weidendo** [comment]
For the record: also breaks compilation on macOS.

I do not remember the discussion. If it is about eventual performance issues, I only care if I see the issue when profiling real LAIK applications. We never want to do fine-grained profiling within LAIK. There are tools for that (sampling, or hooks into MPI calls).

However, it may be useful to allow profile hook injection via LD_PRELOAD (this just needs every LAIK API call to be defined twice with slightly different name, as glibc or MPI is doing).

**Comment by AlexanderKurtz** [comment]
Wasn't this fixed by 86c180e1c16fffa0761a785dad315a7d524e053b?

**Comment by twittidai** [comment]
Done.
