### ISSUE TITLE
Two sets of QtCreator config files in repository

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#48]
There are currently two sets of QtCreator config files in the repository, one in the project root and the other in .qtcreator.

**Comment by weidendo** [comment]
In the root, there should be none. I cannot see any here. Which files?

**Comment by twittidai** [comment]
Plus I suggest that these files does not belong into the repository.

**Comment by AlexanderKurtz** [comment]
@weidendo: e.g. https://github.com/envelope-project/laik/blob/master/laik.config

**Comment by AlexanderKurtz** [comment]
For future reference: This was fixed in 3e6e794fb9ae31229eda0aecef288eeb66c3c543.
