### ISSUE TITLE
configure handles CXX environment variable incorrectly

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#55]
Rebasing PR #47 to git master [revealed the following problem](https://travis-ci.org/envelope-project/laik/jobs/315995993#L1355) which leads to build failures. Here's what happens:

```
alexander@shepard:~/git/laik$ CC=clang CXX=clang++ ./configure 
MQTT enabled (mosquitto + protobuf found).
MPI enabled (using 'mpicc' as compiler wrapper).
C++ support enabled (using 'clang' for C++ examples).
OpenMP activated in examples (using '-fopenmp')
Setting compiler to 'clang' as requested.
Setting C++ compiler to 'clang' as requested.
Generated 'Makefile.config'
alexander@shepard:~/git/laik$ 
```

The line ```Setting C++ compiler to 'clang' as requested.``` is obviously incorrect, I asked for ```clang++```. The difference between the two is marginal when it compiles to compiling, but becomes significant when it comes to linking since ```clang``` obviously does not automaticallu link the ```libstdc++``` as expected.

**Comment by AlexanderKurtz** [comment]
Ok, so I just opened #56 which fixes the immediate problem, but IMHO this is the symptom of two bigger problems:

 1. configure doesn't configure the build system according to what the user wants, but tries to be helpful and enables/disables features automatically based on what its heuristics finds on the host system.
 2. because of 1. we can't force Travis to test all available the features and so this problem went unnoticed.

I really think we should do something about this...

**Comment by weidendo** [comment]
Thanks for catching the typo.

But which problem went unnoticed? We have no C++ test.

"configure" is just meant to be a fast bootstrap mechanism for convenience. Nobody forces you to run it at all. Instead, Makefile.config can be changed directly, also from within Travis.
