### ISSUE TITLE
[SECURITY] configure uses a predictable filename in /tmp

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#57]
https://github.com/envelope-project/laik/blob/master/configure#L100 contains this:

```
tname = "/tmp/laiktest.c"
tfile = open(tname, 'w')
tfile.write("#include <omp.h>\nint main(){return 0;}\n")
tfile.close()
```

This is a security vulnerability [0], please don't do this.
@weidendo: Since you introduced this in 0001f63a34be43589945ce6e3a17aa888056e1bf, what was the problem with using ```/dev/null``` as the code originally did? Especially since the ```-fsyntax-only``` option means that the input file isn't actually read.

[0] https://www.owasp.org/index.php/Insecure_Temporary_File

**Comment by weidendo** [comment]
> cc -fsyntax-only -fopenmp /dev/null
cc: warning: /dev/null: linker input file unused because linking not done

Can we just stop wasting time on something which will be replaced soon?
