### ISSUE TITLE
Travis runs should check the source code with a linter

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#72]
We should define a coding style and enforce it via a linter in Travis. ```clang-tidy``` appears to be suitable.

**Comment by AlexanderKurtz** [comment]
Ok, it seems that CMake can actually generate the ```compile_commands.json``` file needed for clang-tidy itself:

https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html

So, there wouldn't even be a need for a dirty hack like ```bear``` (which traces the compilation process, by intercepting the ```exec(2)``` calls (see https://manpages.debian.org/stretch/bear/bear.1.en.html)

**Comment by AlexanderKurtz** [comment]
Ok, so this works:

Generate the ```compile_commands.json``` file (in the ```build``` directory):
```
cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=1 ..
```

Run the linter:
```
git ls-files -z '*.c' | xargs --null --max-args=1 clang-tidy -p build/compile_commands.json
```

So, I will come back to this once the CMake PR (#64) is merged!

**Comment by weidendo** [comment]
clang-tidy was supported in Travis before we switched to Docker.
Why not just revive it?
