### ISSUE TITLE
Added --prefix="/path/to/install/dir"

### ISSUE THREAD

**Issue by twittidai** [envelope-project/laik#84]
This is useful, for deployment on HPC-alike system.

**Comment by AlexanderKurtz** [comment]
What exactly do you mean here? Something like this?

```
mkdir build
cd build
cmake ..
DESTDIR=/path/to/install/dir make install
```

or

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/dir ..
make install
```

(Note that these these two are NOT the same, see https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_PREFIX.html)

This should work already!

**Comment by twittidai** [comment]
I think the later is better.

**Comment by AlexanderKurtz** [comment]
So... is there still an issue here?

**Comment by AlexanderKurtz** [comment]
Hmm? I still don't understand what exactly you are missing here?

**Comment by twittidai** [comment]
I haven't check it yet, that's why I reopened this.. sorry for the misunderstanding

**Comment by twittidai** [comment]
CMAKE version ist Ok. 
@weidendo now a Makefile version would be great. But if you think it's also ok without, please close this.

**Comment by AlexanderKurtz** [comment]
> CMAKE version ist Ok.

Great!

> @weidendo now a Makefile version would be great. But if you think it's also ok without, please close this.

I think the Makefile already supports this:

https://github.com/envelope-project/laik/blob/master/Makefile#L80

```Make
install_laik: $(LAIKLIB) $(HEADERS)
	cp $(wildcard $(SDIR)include/*.h) $(PREFIX)/include
	mkdir -p $(PREFIX)/include/laik
	cp $(wildcard $(SDIR)include/laik/*.h) $(PREFIX)/include/laik
	#mkdir -p $(PREFIX)/include/interface
	#cp $(wildcard $(SDIR)include/interface/*.h) $(PREFIX)/include/interface
	mkdir -p $(PREFIX)/lib
	cp $(LAIKLIB) $(PREFIX)/lib
```

So somthing like

```
PREFIX=/usr/local make install
```

should work (untested)!

**Comment by weidendo** [comment]
As noted, Makefiles support that, too.
configure passes PREFIX to Makefile.config if set, so this works, too:

PREFIX=/bla ./configure
make install
