### ISSUE TITLE
Decide if __attribute__ ((cleanup)) should be allowed in LAIK

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#97]
I would really like to use ```__attribute__ ((cleanup))``` (or rather its glib wrappers) in my code since it makes error handlung **so** much easier. Unfortunately it isn't standard C though, so I wanted to ask here first.

@weidendo and @twittidai: Could you try to compile and run the code below with the compilers you care about and report whether everything works as expected (i.e. the "Cleanup for %p requested" message is printed correctly)? I have already successfully tried this with recent versions of clang and gcc, but I don't have access to more exotic compilers such as ICC or clang on OS X.

```C
#include <stdio.h>

void destroy (void* data) {
    printf ("Cleanup for %p requested\n", data);
}

int main (int argc, char** argv) {
    (void) argc;
    (void) argv;

    __attribute__ ((cleanup (destroy))) int foo = 0;
}
```

**Comment by weidendo** [comment]
What is this about? Benefit?

To check for memory leaks, there are other tools around
(we can run all tests also within Valgrind in Travis).

**Comment by AlexanderKurtz** [comment]
As I said, this is mainly interesting for error handling. It enables you to write code like this:

```C
int foo (int arg) {
  g_autoptr(Object) object = object_new ();
  if (is_valid (arg)) {
    return object_bar (object, arg);
  } else {
    return -EINVAL;
  }
}
```

This code ensures that ```object``` is always released with the correct, type-specific release function, as soon as the ```object``` variable goes out of scope. Essentially, these are a (very limited and deterministic) form of destructors for C.

Since the code for the TCP backend needs to do a lot of a) memory allocation and b) fragile network operations, it would **really** help me immensely if I could tell the compiler to clean up for me in the case of errors!

Of course, you don't have to use this, but I really would like to, so could you test if the code sample in the first comment works with the mentioned compilers?

**Comment by twittidai** [comment]
This works. Although it seems to work with both gcc, icc and clang, I would use it with caution, since it is only documented as GNU-C feature. 
http://unixwiz.net/techtips/gnu-c-attributes.html

The previous code returns this: 

With Apple CLANG compiler
```
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
```

```
Cleanup for 0x7ffee8f849ec requested
```

With Intel Compiler: 
```
icc version 18.0.0 (gcc version 4.9.0 compatibility)
```

```
Cleanup for 0x7ffee36ba9ec requested
```

**Comment by AlexanderKurtz** [comment]
Thanks @twittidai! I will certainly not add this to LAIK itself, but I will probably make use of it in the TCP backend. It already has a hard dependency on GLib, so this shouldn't matter too much. For the record, here's the final test matrix:

Does $COMPILER support ```__attribute__ ((cleanup (foo)))```?

 * **GCC:** Yes, since at least version 4.0 [0]
 * **Clang:** Yes, since at least version 3.9:
    $ clang-3.9 test.c 
    $ ./a.out 
    Cleanup for 0x7ffd0dd0fa4c requested
    $ 
 * **Apple Clang:** Yes, since at least version 9.0.0 [1]
 * **ICC:** Yes, since at least version 18.0.0 [1]

[0] https://gcc.gnu.org/onlinedocs/gcc-4.0.0/gcc/Variable-Attributes.html
[1] https://github.com/envelope-project/laik/issues/97#issuecomment-368769852

**Comment by weidendo** [comment]
Just to get this right: this is more or less required for using glib?

**Comment by AlexanderKurtz** [comment]
No, GLib doesn't require this itself, as they want to be able to also build with compilers not supporting this feature (e.g. MSVC). However, they do provide some pretty nice macros to make this easy to use and type-safe, see here:

https://blogs.gnome.org/desrt/2015/01/30/g_autoptr/
https://developer.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#g-autoptr
